spring:
  #解决时间到浏览器少8小时情况
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lc?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#加热部署便利开发
#  devtools:
#    restart:
#      enabled: true #设置开启热部署
  freemarker:
    cache: false #页面不加载缓存，修改即时生效

server:
    port: 80
