spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lc?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password:

#没问题啊，这个可以用的
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#加热部署便利开发
#  devtools:
#    restart:
#      enabled: true #设置开启热部署
  freemarker:
    cache: false #页面不加载缓存，修改即时生效

server:
    port: 80
